format = """
[](bold #7aa2f7)\
$os\
[](bold #e0af68)\
$directory\
[](bold #3b4261)\
$git_branch\
$git_status\
$git_state\
$fill\
$nodejs\
$python\
$rust\
$golang\
$java\
$lua\
$bun\
$cmd_duration\
$line_break\
$character"""

right_format = """$time"""

[os]
disabled = false
style = "bold #7aa2f7"
format = "[ $symbol ]($style)"

[os.symbols]
Arch = "󰣇"
Linux = ""
Macos = "󰀵"

[character]
success_symbol = "[  ❯](bold #7aa2f7)"
error_symbol = "[  ❯](bold #f7768e)"
vimcmd_symbol = "[  ❮](bold #9ece6a)"

[directory]
style = "bold #e0af68"
truncation_length = 1
fish_style_pwd_dir_length = 1
format = "[ $path ]($style)[$read_only]($read_only_style)"
read_only = " 󰌾"
read_only_style = "bold #f7768e"

[git_branch]
style = "bold #bb9af7"
symbol = "󰊢"
format = "[ $symbol $branch]($style)"

[git_status]
style = "bold #7dcfff"
format = '([$all_status$ahead_behind]($style))'
conflicted = " =${count}"
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕"
untracked = " ?"
stashed = " ●"
modified = " !"
staged = " +"
renamed = " »"
deleted = " ✘"

[git_state]
style = "bold #e0af68"
format = ' \([$state( $progress_current/$progress_total)]($style)\)'

[fill]
symbol = " "

[nodejs]
style = "bold #7aa2f7"
symbol = "󰎙"
version_format = "${major}.${minor}"
format = "[ $symbol $version]($style)"

[python]
style = "bold #9ece6a"
symbol = "󰌠"
version_format = "${major}.${minor}"
format = '[ $symbol ${version}(\($virtualenv\))]($style)'

[rust]
style = "bold #ff9e64"
symbol = "󱘗"
version_format = "${major}.${minor}"
format = "[ $symbol $version]($style)"

[golang]
style = "bold #7dcfff"
symbol = "󰟓"
version_format = "${major}.${minor}"
format = "[ $symbol $version]($style)"

[java]
style = "bold #f7768e"
symbol = "󰬷"
version_format = "${major}"
format = "[ $symbol $version]($style)"

[lua]
style = "bold #73daca"
symbol = "󰢱"
version_format = "${major}.${minor}"
format = "[ $symbol $version]($style)"

[bun]
style = "bold #bb9af7"
symbol = "󰚩"
version_format = "${major}.${minor}"
format = "[ $symbol $version]($style)"

[cmd_duration]
style = "bold #565f89"
format = "[ $duration]($style)"
min_time = 3_000
show_milliseconds = false

[time]
disabled = false
style = "bold #3b4261"
format = "[ $time]($style)"
time_format = "%I:%M %p"

[line_break]
disabled = false
